language: go
go:
  - 1.13.x

os:
  - linux
#  - osx

dist: trusty
sudo: false

install: true

env:
  - GO111MODULE=on

script:
  - cd wasm-test-suite && go test .
#  - go test ./...

notifications:
  email: true

before_install:
  - go get golang.org/x/tools/cmd/goimports && go install golang.org/x/tools/cmd/goimports
  - docker pull vugu/wasm-test-suite:latest
  - docker run -d -t -p 9222:9222 -p 8846:8846 --name wasm-test-suite vugu/wasm-test-suite:latest

services:
  - docker

